In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("uciml/sms-spam-collection-dataset")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'sms-spam-collection-dataset' dataset.
Path to dataset files: /kaggle/input/sms-spam-collection-dataset

In [5]:
import pandas as pd
import numpy as np

df = pd.read_csv("/kaggle/input/sms-spam-collection-dataset/spam.csv", encoding="latin-1")
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [7]:
df = df[['v1','v2']]

In [8]:
df.columns = ['label','message']

In [9]:
df.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [10]:
df.isnull().sum()

label      0
message    0
dtype: int64

In [11]:
print(df['label'].value_counts())

label
ham     4825
spam     747
Name: count, dtype: int64

In [12]:
df['label'] = df['label'].map({
    'ham':0,
    'spam':1
})

In [13]:
X = df['message']
y = df['label']

In [14]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [15]:
tfidf = TfidfVectorizer(
    stop_words='english',
    max_features=5000
)

In [16]:
X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

#LogisticRegression

In [17]:
model = LogisticRegression()

In [18]:
model.fit(X_train_tfidf, y_train)

LogisticRegression()

In [19]:
y_pred = model.predict(X_test_tfidf)

In [20]:
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy :", accuracy)

Accuracy : 0.9587443946188341

In [21]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.96      1.00      0.98       965
           1       0.97      0.71      0.82       150

    accuracy                           0.96      1115
   macro avg       0.96      0.86      0.90      1115
weighted avg       0.96      0.96      0.96      1115

In [24]:
message = ["Congratulations! You won a free iPhone. Click here now."]
message_tfidf = tfidf.transform(message)
prediction = model.predict(message_tfidf)
if prediction[0] == 1:
    print("Spam")
else:
    print("Ham")

Spam

# NAIVE BAYES

In [26]:
from sklearn.naive_bayes import MultinomialNB

In [27]:
model_naive = MultinomialNB()

model_naive.fit(X_train_tfidf, y_train)

MultinomialNB()

In [28]:
y_pred = model_naive.predict(X_test_tfidf)

In [29]:
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.9730941704035875

In [30]:
from sklearn.svm import LinearSVC
model_svm = LinearSVC()
model_svm.fit(X_train_tfidf, y_train)

LinearSVC()

In [31]:
y_pred = model_svm.predict(X_test_tfidf)

In [32]:
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.9748878923766816

In [33]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      0.99      0.99       965
           1       0.96      0.85      0.90       150

    accuracy                           0.97      1115
   macro avg       0.97      0.92      0.94      1115
weighted avg       0.97      0.97      0.97      1115